language_name: "English"
# login
heading_login: "Please log in"
label_username: "Username"
label_password: "Password"
label_staysignedin: "Remember me"
label_login: "Log in"
# dashboard
welcome_header: "Welcome to OpenDash!"
welcome_paragraph1: "It looks like you signed in the first time. If you need help with a function, you
currently will have to figure it out for yourself. The help section is to be invented yet."
welcome_paragraph2: "Have fun automating your life either way!"
# agents
agents_header: "Your registered agents"
agents_empty_header: "No agents found :("
agents_empty_description: "...yet. Try hitting the \"Scan\" button to search for DashAgents nearby."
agents_scan_button: "Scan"
agent_address: "Address:"
agents_loading_description: "Loading..."
agent_edit_actions: "Edit actions"
agent_edit_name: "Change name"
# modals
modal_edit_actions_table_head_number: "#"
modal_edit_actions_table_head_action: "Currently assigned actions"
modal_edit_actions_title: "Edit actions"
modal_list_actions_description: "This is a list of all currently associated actions. You can delete or modify actions. [TODO: Add connection to actions store]"
modal_add_action_description: "Add action"
modal_add_action_helptext: "Currently, this allows to add a random string to the action-array attribute of a given DashAgent. Later, this should allow to choose from a list of actions, which are in turn created and configured somewhere else."
modal_edit_actions_add_submit: "Add"
modal_save_changes: "Save changes"
modal_close: "Close"
modal_change_name_title: "Change name"
modal_change_name_description: "Enter the name you wish to give to this DashAgent"
modal_change_name_helptext: "Only letters and numbers are allowed [TODO: Validate!]"
# errors
generic_header: "Undefined Fail."
generic_description: "An error occured. Sorry! We cannot determine what went wrong. Best to try and just reload this page. If the error persists, try a reboot of the system. If you feel confident about it, have a look into your logs, they may tell more."
404_header: "Page not found!"
404_description: "If you didn't dabble in the URLs yourself, this shouldn't have happened. Please raise an issue on <a href='https://github.com/Strongground/opendash'>Github</a>."
# form validation
validation_error_email: "That user does not exist"
validation_error_password: "Please check your password"
